// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (handle, display_name, email, password_hash)
VALUES (LOWER($1), $2, LOWER($3), $4)
RETURNING id, handle, display_name, email, created_at, updated_at
`

type CreateUserParams struct {
	Handle       string `json:"handle"`
	DisplayName  string `json:"display_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Handle,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT id, password_hash
FROM users
WHERE email = LOWER($1)
`

type GetUserAuthByEmailRow struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserAuthByEmail(ctx context.Context, email string) (GetUserAuthByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAuthByEmail, email)
	var i GetUserAuthByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, handle, display_name, email, created_at, updated_at
FROM users
WHERE email = LOWER($1)
`

type GetUserByEmailRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, display_name, email, created_at, updated_at
FROM users
WHERE handle = LOWER($1)
`

type GetUserByHandleRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (GetUserByHandleRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i GetUserByHandleRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, handle, display_name, email, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, handle, display_name, email, created_at, updated_at
FROM users
ORDER BY handle
`

type ListUsersRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, handle, display_name, email, created_at, updated_at
`

type UpdateDisplayNameParams struct {
	ID          int32  `json:"id"`
	DisplayName string `json:"display_name"`
}

type UpdateDisplayNameRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (UpdateDisplayNameRow, error) {
	row := q.db.QueryRowContext(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i UpdateDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE users
SET email = LOWER($1),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, handle, display_name, email, created_at, updated_at
`

type UpdateEmailParams struct {
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

type UpdateEmailRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (UpdateEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateEmail, arg.Email, arg.ID)
	var i UpdateEmailRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHandle = `-- name: UpdateHandle :one
UPDATE users
SET handle = LOWER($1),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, handle, display_name, email, created_at, updated_at
`

type UpdateHandleParams struct {
	Handle string `json:"handle"`
	ID     int32  `json:"id"`
}

type UpdateHandleRow struct {
	ID          int32        `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateHandle(ctx context.Context, arg UpdateHandleParams) (UpdateHandleRow, error) {
	row := q.db.QueryRowContext(ctx, updateHandle, arg.Handle, arg.ID)
	var i UpdateHandleRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
